/**
 * Generates supabase/seed.sql from the TypeScript content in src/content so
 * the demo driver and the SQL database can never drift apart. Run with:
 *   node scripts/generate-seed.mjs
 * A vitest parity test compares row counts against the TS content.
 */
import { writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

// Compile the content modules to plain JS so this script has no ts-node dep.
const outDir = mkdtempSync(join(tmpdir(), 'seedgen-'))
execSync(
  `pnpm exec esbuild src/content/questions/index.ts src/content/journeys.ts --bundle --format=esm ` +
    `--outdir=${outDir} --out-extension:.js=.mjs --alias:@=./src --log-level=error`,
  { stdio: 'inherit' },
)
const { questionPacks, allQuestions } = await import(join(outDir, 'questions/index.mjs'))
const { journeys, journeySteps } = await import(join(outDir, 'journeys.mjs'))
rmSync(outDir, { recursive: true, force: true })

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replaceAll("'", "''")}'`)
const arr = (v) =>
  `'{${(v ?? []).map((s) => `"${String(s).replaceAll('"', '\\"')}"`).join(',')}}'`

const lines = [
  '-- AUTO-GENERATED by scripts/generate-seed.mjs — edit src/content/* instead.',
  '',
  '-- question packs',
]
for (const p of questionPacks) {
  lines.push(
    `insert into question_packs (id, slug, title, description, active) values (${q(p.id)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.description)}, ${p.active}) on conflict (id) do nothing;`,
  )
}
lines.push('', '-- questions')
for (const question of allQuestions) {
  const stages = question.stages === 'all' ? [] : question.stages
  lines.push(
    `insert into questions (id, pack_id, format, category, stages, difficulty, sensitivity, estimated_minutes, preferred_weekday, prerequisite_question_id, locale, version, premium, active, ai_follow_up_allowed, text, helper, options) values (` +
      [
        q(question.id),
        q(question.packId),
        q(question.format),
        q(question.category),
        arr(stages),
        question.difficulty,
        question.sensitivity,
        question.estimatedMinutes,
        question.preferredWeekday ?? 'null',
        q(question.prerequisiteQuestionId),
        q(question.locale),
        question.version,
        question.premium,
        question.active,
        question.aiFollowUpAllowed,
        q(question.text),
        q(question.helper ?? null),
        question.options ? `'${JSON.stringify(question.options).replaceAll("'", "''")}'::jsonb` : 'null',
      ].join(', ') +
      `) on conflict (id) do nothing;`,
  )
}
lines.push('', '-- journeys')
for (const j of journeys) {
  const stages = j.stageHint === 'all' ? [] : j.stageHint
  lines.push(
    `insert into journeys (id, slug, title, description, stage_hint, premium, active, "order") values (${q(j.id)}, ${q(j.slug)}, ${q(j.title)}, ${q(j.description)}, ${arr(stages)}, ${j.premium}, ${j.active}, ${j.order}) on conflict (id) do nothing;`,
  )
}
lines.push('', '-- journey steps')
for (const s of journeySteps) {
  lines.push(
    `insert into journey_steps (id, journey_id, "order", title, question_id) values (${q(s.id)}, ${q(s.journeyId)}, ${s.order}, ${q(s.title)}, ${q(s.questionId)}) on conflict (id) do nothing;`,
  )
}
lines.push('')

writeFileSync('supabase/seed.sql', lines.join('\n'))
console.log(
  `seed.sql written: ${questionPacks.length} packs, ${allQuestions.length} questions, ${journeys.length} journeys, ${journeySteps.length} steps`,
)
